#构建：docker-compose build
#启动：docker-compose up -d

services:
  iot-cloud-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: maku-cloud-gateway.jar
    image: maku-cloud-gateway:1.0
    container_name: maku-cloud-gateway
    ports:
      - 8088:8088

  iot-cloud-system:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: maku-cloud-system.jar
    image: maku-cloud-system:1.0
    container_name: maku-cloud-system

  iot-cloud-user:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: maku-cloud-new.jar
    image: maku-cloud-new:1.0
    container_name: maku-cloud-new

  iot-cloud-device:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: maku-cloud-screen.jar
    image: maku-cloud-screen:1.0
    container_name: iot-cloud-screen
